server:
  port: 8000
  servlet:
    context-path: /tifa
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tifa.common.entity
  configuration:
    map-underscore-to-camel-case: true
spring:
  jackson:
    default-property-inclusion: non_null
  config:
    import:
      - jwt.yaml
      - database-dev.yaml
      - system.yaml
logging:
  level:
    root: debug

